- name: Get the MAC address
  tags:
    - test
  tasks:
    - name: Debug
      ansible.builtin.debug: 
        msg: "{{ hostvars[inventory_hostname] }}"

- name: Configure OPNsense static DHCP lease for BIND-DNS server
  hosts: opnsense-test
  tags:
    - opnsense
  connection: local
  module_defaults:
    ansibleguy.opnsense.alias:
      firewall: "{{ hostvars['opnsense-test'].ansible_host }}"
      ssl_verify: false
      api_key: 7Iu+9xxO9w4fwA+Va8tOIRhW4jnLI6GPdzIQr+g8OkAJQy4IG5Uhjt2y619xExDtOUoQ3fqkJ5Aegkuv
      api_secret: YwiI4gP4JifldHQH8h+/rK1fTadpz8F0pea97+RfcJ/mTE3hvSSpXQVoWtLm998ssiJ+15MtJG09Ib3L
  tasks:
    - name: Add a DHCP reservation
      ansibleguy.opnsense.dhcp_reservation:
        ip: '172.18.0.18'
        mac: "{{ hostvars['bind9-test'].ansible_mac }}"
        subnet: '172.18.0.0/24'
        hostname: 'example-host'
        description: 'Static lease for example-host'
        state: present
        reload: true

- name: Set up BIND-DNS server
  become: true
  hosts: bind9-test
  tags:
    - dns
  roles:
    - role: bertvv.bind
      vars:
        bind_allow_query:
          - any
        bind_listen_ipv4:
          - any
        bind_zones:
          - name: itm.internal
            create_reverse_zones: true
            primaries:
              - "{{ hostvars['bind9-test'].ansible_host }}"
            name_servers:
              - ns.itm.internal.
            hosts:
              - name: ns
                ip: "{{ hostvars['bind9-test'].ansible_host }}"
                aliases:
                  - ns1
            networks:
              - '172.18.0'
            allow_update:
              - 172.18.0.1
        bind_recursion: true
        bind_forwarders:
          - 9.9.9.9
          - 1.1.1.1
        bind_dnssec_enable: false
        bind_dns_keys:
          - name: opnsense
            algorithm: hmac-sha512
            secret: "yawQV7dZ1nnHSUuMWcucv1E/dIaQVegJzb228RpJdQe/WYQaiz0+aEbFOTE3OqV2qGxNZxoRZ0PsJ7VjQZjbnQ=="
        bind_extra_include_files:
          - "{{ bind_auth_file }}"

- name: Install prerequisites
  ansible.builtin.import_playbook: install_prerequisites.yml

- name: Configure OPNsense for dynamic DNS updates
  hosts: opnsense-test
  tags:
    - opnsense
  remote_user: root
  tasks:
    - name: Change config.xml OPNsense
      community.general.xml:
        path: /conf/config.xml
        xpath: /opnsense/dhcpd/lan/{{ item.key }}
        state: present
        pretty_print: true
        value: "{{ item.value }}"
      loop: "{{ xml_entries | dict2items }}"
      vars:
        xml_entries:
          enable: "1"
          ddnsdomain: itm.internal
          ddnsdomainprimary: "{{ hostvars['bind9-test'].ansible_host }}"
          ddnsdomainkeyname: opnsense
          ddnsdomainkey: yawQV7dZ1nnHSUuMWcucv1E/dIaQVegJzb228RpJdQe/WYQaiz0+aEbFOTE3OqV2qGxNZxoRZ0PsJ7VjQZjbnQ==
          ddnsdomainalgorithm: hmac-sha512
          ddnsupdate: "1"
