- name: Install prerequisites
  ansible.builtin.import_playbook: install_prerequisites.yml

- name: Create OPNsense Ansible User and API key

  hosts: opnsense-test
  remote_user: root

  tasks:
    - name: Create OPNsense Ansible User
      community.general.xml:
        path: /conf/config.xml
        xpath: /opnsense/system/user[name='ansible']/{{ item.key }}
        state: present
        pretty_print: true
        value: "{{ item.value }}"
      loop: "{{ xml_entries | dict2items }}"
      vars:
        xml_entries:
          password: lookup('community.general.random_string', base64=true, length=16)
          scope: user
          name: ansible
          authorizedkeys: "{{ ssh_keys | b64encode }}"
          comment: User for ansible provisioning
          uid: 2000
          shell: /bin/sh
        ssh_keys: "{{ var_ansible_public_ssh_key }}"

    - name: Add OPNsense Ansible User to Admin-Group
      community.general.xml:
        path: /conf/config.xml
        xpath: /opnsense/system/group[name='admins']/member[text()='2000']
        state: present
        pretty_print: true
        value: "2000"

    - name: Add OPNsense Ansible User API key
      community.general.xml:
        path: /conf/config.xml
        xpath: "/opnsense/system/user[name='ansible']/apikeys/\
          item[key='{{ var_ansible_opnsense_api_key }}']/{{ item.key }}"
        state: present
        pretty_print: true
        value: "{{ item.value }}"
      loop: "{{ xml_entries | dict2items }}"
      vars:
        xml_entries:
          key: "{{ var_ansible_opnsense_api_key }}"
          secret: "{{ var_ansible_opnsense_api_secret}}"

    - name: Reload configuration
      changed_when: false
      ansible.builtin.command:
        cmd: /usr/local/etc/rc.reload_all
