- name: Samba installieren und konfigurieren
  hosts: "{{ var_hosts_fileserver }}"
  become: yes

  # TODO: Benutzernamen und Passwort mit Terraform übergeben
  vars:
    samba_users:
      - name: smbuser
        password: "smbuser"

  tasks:
    # Freigabeordner für Samba erstellen
    - name: Freigabeordner für Samba erstellen
      file:
        path: /srv/samba/shared
        state: directory
        mode: '0775'
        owner: nobody
        group: nogroup

    # Samba-Paket installieren
    - name: Installiere Samba
      package:
        name: samba
        state: present

    # Deaktiviere den samba-ad-dc-Dienst
    - name: Deaktiviere samba-ad-dc
      systemd:
        name: samba-ad-dc
        enabled: no
        state: stopped

    # smb.conf mit einer Vorlage konfigurieren
    - name: Konfiguriere smb.conf
      template:
        src: smb.conf.j2
        dest: /etc/samba/smb.conf
      notify:
        - smbd neu starten

    # Sicherstellen, dass der Samba-Dienst aktiviert und gestartet ist
    - name: smbd-Dienst aktivieren und starten
      service:
        name: smbd
        state: started
        enabled: yes

    # Benutzer erstellen und Passwort setzen
    - name: Systembenutzer für Samba erstellen
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /sbin/nologin
        state: present
      with_items: "{{ samba_users }}"

    - name: Samba-Benutzer hinzufügen und Passwort setzen
      shell: |
        echo -e "{{ item.password }}\n{{ item.password }}" | smbpasswd -a -s {{ item.name }}
      with_items: "{{ samba_users }}"
      args:
        executable: /bin/bash

  handlers:
    - name: smbd neu starten
      service:
        name: smbd
        state: restarted
