- name: Install Samba Server and shares
  hosts: "{{ var_hosts_fileserver }}"
  become: true

  vars:
    linux_samba_groups: "{{ var_samba_groups }}"
    linux_samba_users: "{{ var_samba_users }}"
        
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
      loop: "{{ linux_samba_groups }}"

    - name: Create system user for Samba
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /sbin/nologin
        create_home: false
        state: present
        group: "{{ item.group }}"
        append: true
      loop: "{{ linux_samba_users }}"

    - name: Include Samba Server role
      ansible.builtin.include_role:
        name: vladgh.samba.server
      vars:
        samba_apple_extensions: false
        samba_enable_netbios: false
        samba_security: user
        samba_server_max_protocol: SMB3
        samba_server_min_protocol: SMB2_02
        samba_netbios_name: "{{ ansible_hostname }}"
        samba_server_string: "%m"
        samba_shares:
          - name: Nextcloud Data
            comment: Nextcloud Data store
            browseable: false
            create_mode: "0770"
            directory_mode: "0770"
            force_create_mode: "0000"
            force_directory_mode: "0000"
            owner: nobody
            group: "{{ var_nextcloud_data_owner_group }}"
            path: /srv/shares/nextcloud/data
            valid_users: "{{ var_nextcloud_data_valid_users }}"
            write_list: "{{ var_nextcloud_data_write_list }}"
            writable: true
          - name: Nextcloud Config
            comment: Nextcloud Config store
            browseable: false
            create_mode: "0770"
            directory_mode: "0770"
            force_create_mode: "0000"
            force_directory_mode: "0000"
            owner: nobody
            group: "{{ var_nextcloud_config_owner_group }}"
            path: /srv/shares/nextcloud/config
            valid_users: "{{ var_nextcloud_config_valid_users }}"
            write_list:  "{{ var_nextcloud_config_write_list }}"
            writable: true
        samba_users: "{{ linux_samba_users }}"
        samba_workgroup: WORKGROUP
