- name: Install Docker on Swarm Nodes
  hosts: swarm
  become: true
  tasks:
    # Install prerequisite packages required for Docker and Python integration.
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - python3-pip
          - python3-docker
        state: present
        update_cache: true

    # Download Docker's official GPG key to verify the repository packages.
    - name: Download Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: false

    # Retrieve the system's dpkg architecture to include in the repository configuration.
    - name: Retrieve dpkg architecture
      ansible.builtin.command: dpkg --print-architecture
      register: dpkg_arch_result
      changed_when: false

    # Save the detected architecture as a fact for later use.
    - name: Set dpkg architecture fact  # Saves the architecture as a fact for later use
      ansible.builtin.set_fact:
        dpkg_arch: "{{ dpkg_arch_result.stdout }}"

    # Dynamically retrieve the Ubuntu version codename for proper repository URL formation.
    - name: Retrieve Ubuntu version codename dynamically  # Identifies the Ubuntu version
      ansible.builtin.shell: |
        set -o pipefail && grep 'VERSION_CODENAME=' /etc/os-release | cut -d'=' -f2
      args:
        executable: /bin/bash
      register: codename_result
      changed_when: false

    # Save the Ubuntu version codename as a fact; important for adding the correct repository.
    - name: Set version codename fact dynamically  # Saves the Ubuntu version codename as a fact
      ansible.builtin.set_fact:
        version_codename: "{{ codename_result.stdout }}"

    # Configure apt to use Docker’s repository by adding an entry in the sources list.
    # This uses the architecture and codename facts collected earlier.
    - name: Add Docker to sources list  # Configures apt to use Docker's repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ version_codename }} stable"
        create: true
        state: present
        mode: '0644'

    # Update apt package cache and install Docker packages.
    - name: Update apt-get  # Refreshes the package database and installs Docker packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

- name: Initialize Swarm Manager
  hosts: swarm_manager[0]
  become: true
  tasks:
    # Initialize the Docker Swarm on the first manager node.
    # The advertise_addr is set to the ansible_host value.
    - name: Initialize Docker Swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
      register: swarm_init  # Register the output to use join tokens for other nodes

- name: Join remaining Manager Nodes to Swarm
  hosts: swarm_manager:!swarm_manager[0]
  become: true
  tasks:
    # Join additional manager nodes using the join token retrieved from the first manager.
    - name: Join Docker Swarm Cluster
      community.docker.docker_swarm:
        state: join
        join_token: "{{ hostvars[groups['swarm_manager'][0]].swarm_init.swarm_facts.JoinTokens.Manager }}"
        remote_addrs:
          - "{{ hostvars[groups['swarm_manager'][0]].ansible_host }}"

- name: Join Worker Nodes to Swarm
  hosts: swarm_worker
  become: true
  tasks:
    # Join worker nodes to the Docker Swarm using the worker join token.
    - name: Join Docker Swarm Cluster
      community.docker.docker_swarm:
        state: join
        join_token: "{{ hostvars[groups['swarm_manager'][0]].swarm_init.swarm_facts.JoinTokens.Worker }}"
        remote_addrs:
          - "{{ hostvars[groups['swarm_manager'][0]].ansible_host }}"
